baseURL = "https://kolakows.github.io/"
languageCode = "en-us"
title = "Igor's Blog"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true

[params.homeInfoParams]
  Title = "ðŸ‘‹ Welcome to my blog"
  Content = "Hi, this is Igor. I'm documenting my projects and writing about other things in this blog."

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/kolakows"

#[[params.socialIcons]]
#  name = "twitter"
#  url = "https://twitter.com/yourusername"

[params.assets]
    favicon = "/favicon.svg"
